apiVersion: apps/v1
kind: Deployment
metadata:
    name: financial-data
    namespace: test
    labels:
        app: financial-data
spec:
    replicas: 1
    selector:
        matchLabels:
            app: financial-data
    template:
        metadata:
            labels:
                app: financial-data
        spec:
            containers:
            - name: financial-data
              image: financial-data:1.1
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: financial-data
    namespace: test
spec:
    type: ClusterIP
    ports:
    - port: 8080
    selector:
        app: financial-data